### ISSUE TITLE
CRM says its not a managed solution

### ISSUE THREAD

**Issue by EnterPro777** [JPkenpachi1/PCF_Components#1]
When importing the solution from the solutions Folder (bin/debug), CRM says its not a managed solution.

**Comment by MissyM** [comment]
There is an error when I try to `npm run built`:
`pcf-scripts] [Error] encountered unexpected error:
Error: No ESLint configuration found in /Users/mile/source/PCF_Components/Training101.`

**Comment by JPkenpachi1** [comment]
Which repo?
